apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    operator.tekton.dev/release: devel
    version: v0.23.0-2
  name: tekton-operator
  namespace: tekton-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tekton-operator
  template:
    metadata:
      labels:
        app: tekton-operator
        name: tekton-operator
    spec:
      containers:
        - env:
            - name: IMAGE_PIPELINES_PROXY
              value: gcr.io/tekton-releases/github.com/tektoncd/operator/cmd/kubernetes/webhook:v0.23.0-2@sha256:f359bf33d2cb6073f1b19b04cd76f6d341aa5a2ddd485c9a10a5b234d8fb4db0
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: tekton-operator
          image: gcr.io/tekton-releases/github.com/tektoncd/operator/cmd/kubernetes/operator:v0.23.0-2@sha256:bc04c98f9a0aee94b5be740e2818a043383475347a576e766a984933d4e8999f
          imagePullPolicy: Always
          name: tekton-operator
      serviceAccountName: tekton-operator

---
