name: checking-updates

on:
  push:
    branches:
      - "testing-ci"

jobs:
  raw manifest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Check last upstream version
      id: lastrelease
      run: |
        get_latest_release() {
          curl -s "https://api.github.com/repos/tektoncd/operator/releases" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'|head -n 1
        }
        echo "::set-output name=latest_tag::$(get_latest_release)"
    - name: execute hack
      id: hack
      env:
        RELEASE: {{ steps.lastrelease.outputs.latest_tag }}
      run: |
        cd deploy
        ../hack/new-release.sh ${RELEASE}
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Update to version {{ steps.lastrelease.outputs.latest_tag }}
        branch: master
        file_pattern: deploy/*.yaml
        tagging_message: {{ steps.lastrelease.outputs.latest_tag }}
