name: checking updates

on:
  push:
    branches:
      - "testing-ci"

jobs:
  raw-manifests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check last upstream version
      id: lastrelease
      run: |
        get_latest_release() {
          curl -s "https://api.github.com/repos/tektoncd/operator/releases" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'|head -n 1
        }
        echo "::set-output name=latest_tag::$(get_latest_release)"
    - name: execute hack
      id: hack
      env:
        RELEASE: ${{ steps.lastrelease.outputs.latest_tag }}
      run: |
        wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq
        chmod +x /usr/bin/yq
        cd deploy
        ../hack/new-release.sh ${RELEASE}
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Update to version {{ steps.lastrelease.outputs.latest_tag }}
        branch: master
        file_pattern: deploy/*.yaml
        tagging_message: ${{ steps.lastrelease.outputs.latest_tag }}
